# Constants_Sequences_and_Random_Values

In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.InteractiveSession()

Q1. Create a tensor of the shape [2, 3] with all elements set to zero.


In [8]:
out = tf.zeros([2, 3])
print out.eval()
assert np.allclose(out.eval(), np.zeros([2, 3]))

[[ 0.  0.  0.]
 [ 0.  0.  0.]]


Q2. Let x be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as X with all elements set to zero.

In [11]:
arr = np.array([[1,2,3], [4,5,6]])
x = tf.convert_to_tensor(arr)
out = tf.zeros_like(x)
print out.eval()
assert np.allclose(out.eval(), np.zeros_like(arr))

[[0 0 0]
 [0 0 0]]


Q3. Create a tensor of shape [2, 3] with all elements set to one.

In [13]:
out = tf.ones([2, 3])
print out.eval()
assert np.allclose(out.eval(), np.ones([2, 3]))

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


Q4. Let x be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as x with all elements set to one.

In [15]:
arr = np.array([[1,2,3], [4,5,6]])
x = tf.convert_to_tensor(arr)
out = tf.ones_like(x)
print out.eval()
assert np.allclose(out.eval(), np.ones_like(arr))

[[1 1 1]
 [1 1 1]]


Q5. Create a tensor of the shape [3, 2], with all elements of 5.

In [19]:
out1 = tf.fill([3, 2], 5)
out2 = tf.ones([3, 2]) * 5
assert np.allclose(out1.eval(), out2.eval())
assert np.allclose(out1.eval(), np.full([3, 2], 5))
print out1.eval()

[[5 5]
 [5 5]
 [5 5]]


/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full([3, 2], 5) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


Q6. Create a constant tensor of [[1, 3, 5], [4, 6, 8]].

In [21]:
out = tf.constant([[1, 3, 5], [4, 6, 8]], name="out_tensor")
print out.eval()
assert np.allclose(out.eval(), np.array([[1, 3, 5], [4, 6, 8]]))

[[1 3 5]
 [4 6 8]]


Q7. Create a constant tensor of the shape [2, 3], with all elements set to 4.

In [23]:
out = tf.constant(4, shape=[2, 3])
print out.eval()
assert np.allclose(out.eval(), np.full([2, 3], 4))

[[4 4 4]
 [4 4 4]]


/usr/local/lib/python2.7/dist-packages/numpy/core/numeric.py:301: FutureWarning: in the future, full([2, 3], 4) will return an array of dtype('int64')
  format(shape, fill_value, array(fill_value).dtype), FutureWarning)


Q8. Create a 1-D tensor of 50 evenly spaced elements between 5 and 10 inclusive.

In [25]:
out = tf.linspace(5., 10., 50)
print out.eval()
assert np.allclose(out.eval(), np.linspace(5., 10., 50))

[  5.           5.10204077   5.20408154   5.3061223    5.40816307
   5.51020432   5.61224508   5.71428585   5.81632662   5.91836739
   6.02040815   6.12244892   6.22448969   6.32653046   6.4285717
   6.53061247   6.63265324   6.734694     6.83673477   6.93877554
   7.04081631   7.14285755   7.24489784   7.34693909   7.44897938
   7.55102062   7.65306139   7.75510216   7.85714293   7.95918369
   8.06122494   8.16326523   8.26530647   8.36734676   8.46938801
   8.5714283    8.67346954   8.77551079   8.87755108   8.97959232
   9.08163261   9.18367386   9.2857151    9.38775539   9.48979568
   9.59183693   9.69387817   9.79591846   9.89795876  10.        ]


Q9. Create a tensor which looks like [10, 12, 14, 16, ..., 100].

In [27]:
out = tf.range(10, 101, 2)
print out.eval()
assert np.allclose(out.eval(), np.arange(10, 101, 2))

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


Q10. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=2.

In [41]:
out = tf.random_normal([3, 2], 0, 2.)
print out.eval()
comp = np.random.normal(0, 2., [3, 2])
print comp

[[-0.7510317  -1.24089944]
 [ 1.22353458  1.61628652]
 [ 1.4566102   0.46739912]]
[[-1.09279953  0.23440898]
 [-3.10955411 -2.93789868]
 [ 4.43819785 -0.99598223]]


Q11. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=1 such that any values don't exceed 2 standard deviations from the mean.

In [42]:
out = tf.truncated_normal([3, 2])
print out.eval()

[[-0.69565105 -0.53550154]
 [ 0.36046204  1.53484821]
 [ 1.96950996 -0.01210264]]


Q12. Create a random tensor of the shape [3, 2], with all elements from a uniform distribution that ranges from 0 to 2 (exclusive).

In [45]:
out = tf.random_uniform([3, 2], 0, 2)
print out.eval()
comp = np.random.uniform(0, 2, [3, 2])
print comp

[[ 1.7810514   0.348804  ]
 [ 1.62487888  0.39923024]
 [ 1.8295908   0.74323106]]
[[ 0.27514004  0.32266683]
 [ 0.16925557  1.93464822]
 [ 1.16343895  0.8267628 ]]


Q13. Let x be a tensor of [[1, 2], [3, 4], [5, 6]]. Shuffle X along its first dimension.

In [55]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
x = tf.constant(arr)
out = tf.random_shuffle(x)
print out.eval()
comp = arr
np.random.shuffle(comp)
print comp

[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]


Q14. Let x be a random tensor of the shape [ 10, 10, 3], with elements from a unit normal distribution. Crop x with the size of [5, 5, 3].

In [56]:
x = tf.random_normal([10, 10, 3])
out = tf.random_crop(x, [5, 5, 3])
print out.eval()

[[[ 0.46845943 -0.64245254 -0.53580236]
  [-0.35512397 -1.98819721  0.39298338]
  [ 0.9148674   0.38293061  1.1951946 ]
  [ 1.32107627 -0.08874734  0.87916815]
  [ 0.99050045 -2.47990561 -0.52326751]]

 [[ 0.35562405  0.75450194  0.48131341]
  [-0.59869409 -0.25912714 -0.11784804]
  [ 0.50158823  2.13370299 -0.3135336 ]
  [ 1.76679182  0.20238815 -0.3087104 ]
  [-0.41599715 -1.17480087 -1.29153204]]

 [[-1.76183093 -1.44202971  2.78601289]
  [-1.50471473  0.69991964 -0.44135454]
  [-0.2802043  -0.74777472  0.65097976]
  [-0.90484023  0.0474993  -1.0748539 ]
  [-0.17384501 -0.67117465  1.05855751]]

 [[ 1.35165524  1.47297788  0.16402504]
  [ 0.40435961  0.29287887 -0.59426469]
  [ 0.08936089 -1.05115104  1.81685352]
  [-1.54332256  1.53148067 -0.51505107]
  [ 1.7882725  -1.11887681  0.22252357]]

 [[ 1.23406482 -0.89880151 -0.34322438]
  [ 0.72665292  1.08894777  0.75747514]
  [-0.56236416 -0.7856887  -1.57206285]
  [ 0.72111505 -1.01569891 -0.05111056]
  [ 0.23288217 -0.78203732 -2.10