# Math Part 1

In [12]:
__author__ = "kyubyong. kbpark.linguist@gmail.com. https://www.github.com/kyubyong"

Some Note: if a variable name starts with _, it is a numpy array. I use it explicitly in order to compare tensorflow functions with numpy functions.

In [2]:
import tensorflow as tf
import numpy as np

In [2]:
tf.__version__

'0.12.0-rc1'

In [10]:
np.__version__

'1.11.2'

In [11]:
import sys
sys.version_info # python version

sys.version_info(major=3, minor=5, micro=1, releaselevel='final', serial=0)

In [2]:
sess = tf.InteractiveSession()

## Arithmetic Operators

Q1. Add x and y element-wise.

In [56]:
_x = np.array([1, 2, 3])
_y = np.array([-1, -2, -3])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)

[0 0 0]


Q2. Subtract y from x element-wise.

In [8]:
_x = np.array([3, 4, 5])
_y = np.array(3)
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)

[0 1 2]


Q3. Multiply x by y element-wise.

In [53]:
_x = np.array([3, 4, 5])
_y = np.array([1, 0, -1])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)


[ 3  0 -5]


Q4. Multiply x by 5 element-wise.

In [57]:
_x = np.array([1, 2, 3])
x = tf.convert_to_tensor(_x)


[ 5 10 15]


Q5. Predict the result of this.

In [3]:
_x = np.array([10, 20, 30], np.int32)
_y = np.array([2, 3, 5], np.int32)
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)
out1 = tf.div(x, y)
out2 = tf.truediv(x, y)
#print(np.array_equal(out1.eval(), out2.eval()))


Q6. Get the remainder of x / y element-wise.

In [81]:
_x = np.array([10, 20, 30], np.int32)
_y = np.array([2, 3, 7], np.int32)
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)



[0 2 2]


Q7. Compute the pairwise cross product of x and y.

In [92]:
_x = np.array([1, 2, 3], np.int32)
_y = np.array([4, 5, 6], np.int32)
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)


[-3  6 -3]


## Basic Math Functions

Q8. Add x, y, and z element-wise.

In [9]:
_x = np.array([1, 2, 3], np.int32)
_y = np.array([4, 5, 6], np.int32)
_z = np.array([7, 8, 9], np.int32)
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)
z = tf.convert_to_tensor(_y)


[ 9 12 15]


Q9. Compute the absolute value of x.

In [17]:
_x = np.array([[1, -1], [3, -3]])
x = tf.convert_to_tensor(_x)


[[1 1]
 [3 3]]


Q10. Compute numerical negative value of x, elemet-wise.


In [22]:
_x = np.array([1, -1])
x = tf.convert_to_tensor(_x)


[-1  1]


Q11. Compute an element-wise indication of the sign of x, element-wise.

In [25]:
_x = np.array([1, 3, 0, -1, -3])
x = tf.convert_to_tensor(_x)


[ 1  1  0 -1 -1]


Q12. Compute the reciprocal of x, element-wise.

In [30]:
_x = np.array([1, 2, 2/10])
x = tf.convert_to_tensor(_x)


[ 1.   0.5  5. ]


Q13. Compute the square of x, element-wise.

In [40]:
_x = np.array([1, 2, -1])
x = tf.convert_to_tensor(_x)


[1 4 1]


Q14. Predict the results of this, paying attention to the difference among the family functions.

In [4]:
_x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])
x = tf.convert_to_tensor(_x)

out1 = tf.round(x)
out2 = tf.floor(x)
out3 = tf.ceil(x)
#print(out1.eval())
#print(out2.eval())
#print(out3.eval())


Q15. Compute square root of x element-wise.

In [72]:
_x = np.array([1., 4., 9.])
x = tf.convert_to_tensor(_x)


[ 1.  2.  3.]


Q16. Compute the reciprocal of square root of x element-wise.

In [5]:
_x = np.array([1., 4., 9.])
x = tf.convert_to_tensor(_x)


[ 1.          0.5         0.33333333]


Q17. Compute $x^y$, element-wise.

In [13]:
_x = np.array([[1, 2], [3, 4]])
_y = np.array([[1, 2], [1, 2]])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)


[[ 1  4]
 [ 3 16]]


Q17. Compute $e^x$, element-wise.

In [38]:
_x = np.array([1., 2., 3.], np.float32)
x = tf.convert_to_tensor(_x)


[  2.71828175   7.38905621  20.08553696]


Q18. Compute natural logarithm of x element-wise.

In [50]:
_x = np.array([1, np.e, np.e**2])
x = tf.convert_to_tensor(_x)


[ 0.  1.  2.]


Q19. Compute the max of x and y element-wise.

In [58]:
_x = np.array([2, 3, 4])
_y = np.array([1, 5, 2])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)


[2 5 4]


Q20. Compute the min of x and y element-wise.

In [60]:
_x = np.array([2, 3, 4])
_y = np.array([1, 5, 2])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)


[1 3 2]


Q21. Compuete the sine, cosine, and tangent of x, element-wise.

In [76]:
_x = np.array([-np.pi, np.pi, np.pi/2])
x = tf.convert_to_tensor(_x)


[ -1.22464680e-16   1.22464680e-16   1.00000000e+00]
[ -1.00000000e+00  -1.00000000e+00   6.12323400e-17]
[  1.22464680e-16  -1.22464680e-16   1.63312394e+16]


Q22. Compute (x - y)(x - y) element-wise.

In [77]:
_x = np.array([2, 3, 4])
_y = np.array([1, 5, 1])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)


[1 4 9]
