# Math Part 2

In [1]:
__author__ = "kyubyong. kbpark.linguist@gmail.com. https://www.github.com/kyubyong"

Note: if a variable's name starts with _, it is a numpy array. I use it explicitly in order to compare tensorflow functions with numpy functions.

In [1]:
import tensorflow as tf
import numpy as np

In [5]:
tf.__version__

'0.12.0-rc1'

In [6]:
np.__version__

'1.11.2'

In [7]:
import sys
sys.version_info # python version

sys.version_info(major=3, minor=5, micro=1, releaselevel='final', serial=0)

In [2]:
sess = tf.InteractiveSession()

## Matrix Math Functions

Q1. Create a diagonal tensor with the diagonal values of x.

In [17]:
_x = np.array([1, 2, 3, 4])
x = tf.convert_to_tensor(_x)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Q2. Extract the diagonal of x.

In [21]:
_x = np.array(
[[1, 0, 0, 0],
 [0, 2, 0, 0],
 [0, 0, 3, 0],
 [0, 0, 0, 4]])
x = tf.convert_to_tensor(_x)


[1 2 3 4]


Q3. Permutate the dimensions of x such that the new tensor has shape (3, 4, 2).

In [37]:
_x = np.random.rand(2,3,4)
x = tf.convert_to_tensor(_x)


(3, 4, 2)


Q4. Construct a 3 by 3 identity matrix.

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Q5. Predict the result of this.

In [3]:
_x = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
x = tf.convert_to_tensor(_x)

diagonal_tensor = tf.matrix_diag(x)
diagonal_part = tf.matrix_diag_part(diagonal_tensor)

#print("diagonal_tensor =\n", diagonal_tensor.eval())
#print("diagonal_part =\n", diagonal_part.eval())


Q6. Transpose the last two dimensions of x.

In [49]:
_x = np.random.rand(1, 2, 3, 4)
x = tf.convert_to_tensor(_x)




(1, 2, 4, 3)


Q7. Multiply x by y.

In [50]:
_x = np.array([[1, 2, 3], [4, 5, 6]])
_y = np.array([[1, 1], [2, 2], [3, 3]])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)



[[14 14]
 [32 32]]


Q8. Multiply slices of x and y in batches.

In [56]:
_x = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
_y = np.array([[[1, 1], [2, 2], [3, 3]], [[1, 1], [2, 2], [3, 3]]])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)


[[[14 14]
  [32 32]]

 [[14 14]
  [32 32]]]


Q9. Compute the determinant of x.

In [67]:
_x = np.arange(1, 5, dtype=np.float32).reshape((2, 2))
x = tf.convert_to_tensor(_x)



-2.0


Q10. Compute the inverse of x.


In [84]:
_x = np.arange(1, 5, dtype=np.float64).reshape((2, 2))
x = tf.convert_to_tensor(_x)


[[-2.   1. ]
 [ 1.5 -0.5]]


Q11. Get the lower-trianglular in the Cholesky decomposition of x.

In [91]:
_x = np.array([[4, 12, -16], [12, 37, -43], [-16, -43, 98]], np.float32)
x = tf.convert_to_tensor(_x)



[[ 2.  0.  0.]
 [ 6.  1.  0.]
 [-8.  5.  3.]]


Q12. Compute the eigenvalues and eigenvectors of x.

In [104]:
_x = np.diag((1, 2, 3))
x = tf.convert_to_tensor(_x, tf.float32)



eigentvalues =
 [ 1.  2.  3.]
eigenvectors =
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


Q13. Compute the singular values of x.

In [118]:
_x = np.array(
[[1, 0, 0, 0, 2], 
 [0, 0, 3, 0, 0], 
 [0, 0, 0, 0, 0], 
 [0, 2, 0, 0, 0]], dtype=np.float32)
x = tf.convert_to_tensor(_x)


[ 3.          2.23606801  2.          0.        ]


## Reduction

Q14. Predict the results of these.

In [4]:
_x = np.array(
    [[1, 2, 3, 4],
     [5, 6, 7, 8]])
x = tf.convert_to_tensor(_x)

outs = [tf.reduce_sum(x),
        tf.reduce_sum(x, axis=0),
        tf.reduce_sum(x, axis=1, keep_dims=True),
        "",
        tf.reduce_prod(x),
        tf.reduce_prod(x, axis=0),
        tf.reduce_prod(x, axis=1, keep_dims=True),
        "",
        tf.reduce_min(x),
        tf.reduce_min(x, axis=0),
        tf.reduce_min(x, axis=1, keep_dims=True),
        "",
        tf.reduce_max(x),
        tf.reduce_max(x, axis=0),
        tf.reduce_max(x, axis=1, keep_dims=True),
        "",
        tf.reduce_mean(x),
        tf.reduce_mean(x, axis=0),
        tf.reduce_mean(x, axis=1, keep_dims=True)
           ]
           
for out in outs:
    if out == "":
        #print()
        pass
    else:
#         print("->", out.eval())
        pass


Q15. Predict the results of these.

In [5]:
_x = np.array([[True, True],
              [False, False]])
x = tf.convert_to_tensor(_x)

outs = [tf.reduce_all(x),
        tf.reduce_all(x, axis=0),
        tf.reduce_all(x, axis=1, keep_dims=True),
        "",
        tf.reduce_any(x),
        tf.reduce_any(x, axis=0),
        tf.reduce_any(x, axis=1, keep_dims=True),
        ]

for out in outs:
    if out == "":
#         print()
        pass
    else:
#         print("->", out.eval())
        pass


Q16. Predict the results of these.

In [6]:
_x = np.array([[0, 1, 0],
              [1, 1, 0]])
x = tf.convert_to_tensor(_x)

outs = [tf.count_nonzero(x),
        tf.count_nonzero(x, axis=0),
        tf.count_nonzero(x, axis=1, keep_dims=True),
        ]

for out in outs:
#     print("->", out.eval())
    pass


Q17. Complete the einsum function that would yield the same result as the given function.

In [160]:
_x = np.arange(1, 7).reshape((2, 3))
_y = np.arange(1, 7).reshape((3, 2))

x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)

# Matrix multiplication
out1 = tf.matmul(x, y)
out1_ = tf.einsum('...', x, y)
assert np.allclose(out1.eval(), out1_.eval())

# Dot product
flattened = tf.reshape(x, [-1])
out2 = tf.reduce_sum(tf.mul(flattened, flattened))
out2_ = tf.einsum('...', flattened, flattened)
assert np.allclose(out2.eval(), out2_.eval())

# Outer product
expanded_a = tf.expand_dims(flattened, 1) # shape: (6, 1)
expanded_b = tf.expand_dims(flattened, 0) # shape: (1, 6)
out3 = tf.matmul(expanded_a, expanded_b)
out3_ = tf.einsum('...', flattened, flattened)
assert np.allclose(out3.eval(), out3_.eval())

# Transpose
out4 = tf.transpose(x) # shape: (3, 2)
out4_ = tf.einsum('...', x)
assert np.allclose(out4.eval(), out4_.eval())