# Math Part 3

In [1]:
__author__ = "kyubyong. kbpark.linguist@gmail.com. https://www.github.com/kyubyong"

Note: if a variable's name starts with _, it is a numpy array. I use it explicitly in order to compare tensorflow functions with numpy functions.

In [1]:
import tensorflow as tf
import numpy as np

In [5]:
tf.__version__

'0.12.0-rc1'

In [6]:
np.__version__

'1.11.2'

In [7]:
import sys
sys.version_info # python version

sys.version_info(major=3, minor=5, micro=1, releaselevel='final', serial=0)

In [2]:
sess = tf.InteractiveSession()

## Scan

Q1. Compute the cumulative sum of x along axis 1.

In [11]:
_x = np.array([[1,2,3], [4,5,6]])
x = tf.convert_to_tensor(_x)



[[ 1  3  6]
 [ 4  9 15]]


Q2. Compute the cumulative product of x along axis 1.

In [13]:
_x = np.array([[1,2,3], [4,5,6]])
x = tf.convert_to_tensor(_x)



[[  1   2   6]
 [  4  20 120]]


## Segmentation

Q3. Compute the sum along the first two elements and 
the last two elements of x separately.

In [34]:
_x = np.array(
    [[1,2,3,4], 
     [-1,-2,-3,-4], 
     [-10,-20,-30,-40],
     [10,20,30,40]])
x = tf.convert_to_tensor(_x)


[[0 0 0 0]
 [0 0 0 0]]


Q4. Compute the product along the first two elements and the last two elements of x separately.

In [36]:
_x = np.array(
    [[1,2,3,4], 
     [1,1/2,1/3,1/4], 
     [1,2,3,4],
     [-1,-1,-1,-1]])
x = tf.convert_to_tensor(_x)


[[ 1.  1.  1.  1.]
 [-1. -2. -3. -4.]]


Q5. Compute the minimum along the first two elements and the last two elements of x separately.

In [38]:
_x = np.array(
    [[1,4,5,7], 
     [2,3,6,8], 
     [1,2,3,4],
     [-1,-2,-3,-4]])
x = tf.convert_to_tensor(_x)


[[ 1  3  5  7]
 [-1 -2 -3 -4]]


Q6. Compute the maximum along the first two elements and the last two elements of x separately.

In [39]:
_x = np.array(
    [[1,4,5,7], 
     [2,3,6,8], 
     [1,2,3,4],
     [-1,-2,-3,-4]])
x = tf.convert_to_tensor(_x)


[[2 4 6 8]
 [1 2 3 4]]


Q7. Compute the mean along the first two elements and the last two elements of x separately.

In [54]:
_x = np.array(
    [[1,2,3,4], 
     [5,6,7,8], 
     [-1,-2,-3,-4],
     [-5,-6,-7,-8]])
x = tf.convert_to_tensor(_x)


[[ 3  4  5  6]
 [-3 -4 -5 -6]]


Q8. Compute the sum along the second and fourth and 
the first and third elements of x separately in the order.

In [58]:
_x = np.array(
    [[1,2,3,4], 
     [-1,-2,-3,-4], 
     [-10,-20,-30,-40],
     [10,20,30,40]])
x = tf.convert_to_tensor(_x)


[[  9  18  27  36]
 [ -9 -18 -27 -36]]


## Sequence Comparison and Indexing 


Q9. Get the indices of maximum and minimum values of x along the second axis.


In [67]:
_x = np.random.permutation(10).reshape(2, 5)
print("_x =", _x)
x = tf.convert_to_tensor(_x)



_x = [[8 9 6 0 7]
 [2 4 3 1 5]]
[1 4]
[3 3]


Q10. Find the unique elements of x that are not present in y.

In [78]:
_x = np.array([0, 1, 2, 5, 0])
_y = np.array([0, 1, 4])
x = tf.convert_to_tensor(_x)
y = tf.convert_to_tensor(_y)


[2 5]


Q11. Return the elements of x, if x < 4, otherwise x*10.

In [98]:
_x = np.arange(1, 10).reshape(3, 3)
x = tf.convert_to_tensor(_x)



[[ 1  2  3]
 [40 50 60]
 [70 80 90]]


Q12. Get unique elements and their indices from x.

In [3]:
_x = np.array([1, 2, 6, 4, 2, 3, 2])
x = tf.convert_to_tensor(_x)

out, indices = tf.unique(x)


[1 2 6 4 3]
[0 1 2 3 1 4 1]


Q13. Compute the edit distance between hypothesis and truth.

In [171]:
# Check the documentation on tf.SparseTensor if you are not
# comfortable with sparse tensor.
hypothesis = tf.SparseTensor(
    [[0, 0],[0, 1],[0, 2],[0, 4]],
    ["a", "b", "c", "a"],
    (1, 5)) 
# Note that this is equivalent to the dense tensor.
# [["a", "b", "c", 0, "a"]]

truth = tf.SparseTensor(
    [[0, 0],[0, 2],[0, 4]],
    ["a", "c", "b"],
    (1, 6))
# This is equivalent to the dense tensor.
# [["a", 0, "c", 0, "b", 0]]


[ 2.]
[ 0.66666669]
